Rails.application.routes.draw do
  root 'welcome#index'
  get '/shelters', to: 'shelters#index'
  get '/shelters/new', to: 'shelters#new'
  get '/shelters/:id', to: 'shelters#show'
  get '/shelters/:id/pets', to: 'shelters#showpets'
  get '/shelters/:id/pets/new', to: 'pets#new'
  post '/shelters/:id/pets/new', to: 'pets#create'
  get '/shelters/:id/edit', to: 'shelters#edit'
  get '/shelters/:id/delete', to: 'shelters#destroy'
  get '/pets', to: 'pets#index'
  get '/pets/:id', to: 'pets#show'
  get '/pets/:id/edit', to: 'pets#edit'
  post '/shelters/new_shelter', to: 'shelters#create'
  patch '/shelters/:id/edit', to: 'shelters#update'
  patch '/pets/:id/edit', to: 'pets#update'
  get '/pets/:id/delete', to: 'pets#destroy'
end
